
version: {build}

assembly_info:
  patch: false

before_build:
  - gitversion /l console /output buildserver /updateAssemblyInfo MyLib\Properties\AssemblyInfo.cs
  - appveyor UpdateBuild -Version "%GitVersion_SemVer%"
  - nuget restore

build:
  publish_nuget: false
  verbosity: minimal

after_build:
  - nuget pack MyLib\MyLib.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"

artifacts:
  - path: MyLib.$(GitVersion_NuGetVersion).nupkg
  - path: MyLib\bin\$(CONFIGURATION)
    name: MyLib-$(GitVersion_NuGetVersion).zip

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true